### ISSUE TITLE
Chown typo?

### ISSUE THREAD

**Issue by lukasvitroleracc** [StefanieD/pimcore-docker-setup#5]
Hello,

shouldnt it be "run chown -R www-data:www-data pimcore" instead of "run chown -R 1000:1000 pimcore"?

**Comment by StefanieD** [comment]
Hi,
inside the container every command will be run as root. 
The synched volumes have the ID of the current user. I'm not sure if it's always 1000. But in my case it's 1000.

I just tested it without changing the owner. I think you can ignore the chown command. Or try to set the user directly in the Dockerfile.
But you'll need to give the /var directory the right permissions. Otherwise you'll get the exception that cache files can not be written.
